### ISSUE TITLE
magicento crash after update of PhpStorm to 8.0.2

### ISSUE THREAD

**Issue by yatsyukv** [enriquepiatti/Magicento#141]
Hi.

Faced with total and constant magicento crash after updating PhpStorm to latest build (PS-139.496)

Here is the exception (having hundreds of them - all are the same)

com/intellij/ide/reporter/ConnectionException
java.lang.NoClassDefFoundError: com/intellij/ide/reporter/ConnectionException
    at com.magicento.models.magicento.MagicentoLocalUser.load(MagicentoLocalUser.java:42)
    at com.magicento.MagicentoProjectComponent.isEnabled(MagicentoProjectComponent.java:253)
    at com.magicento.MagicentoProjectComponent.isEnabled(MagicentoProjectComponent.java:235)
    at com.magicento.MagicentoProjectComponent.isDisabled(MagicentoProjectComponent.java:229)
    at com.magicento.extensions.BlockTypeProvider2.getType(BlockTypeProvider2.java:39)
    at com.jetbrains.php.lang.psi.resolve.types.PhpTypeInfo$1.internalCompute(PhpTypeInfo.java:43)
    at com.jetbrains.php.lang.psi.resolve.types.PhpTypeInfo$1.internalCompute(PhpTypeInfo.java:37)
    at com.intellij.openapi.util.Computable$NotNullCachedComputable.compute(Computable.java:52)
    at com.intellij.openapi.util.RecursionManager$2.doPreventingRecursion(RecursionManager.java:112)
    at com.intellij.openapi.util.RecursionManager.doPreventingRecursion(RecursionManager.java:68)
    at com.jetbrains.php.lang.psi.resolve.types.PhpTypeInfo.getType(PhpTypeInfo.java:37)
    at com.jetbrains.php.lang.psi.stubs.PhpFieldElementType.createStub(PhpFieldElementType.java:28)
    at com.jetbrains.php.lang.psi.stubs.PhpFieldElementType.createStub(PhpFieldElementType.java:18)
    at com.intellij.psi.stubs.DefaultStubBuilder.buildStubTreeFor(DefaultStubBuilder.java:60)
    at com.intellij.psi.stubs.DefaultStubBuilder.buildStubTree(DefaultStubBuilder.java:36)
    at com.intellij.psi.impl.source.PsiFileImpl.calcStubTree(PsiFileImpl.java:989)
    at com.intellij.psi.stubs.StubProcessingHelperBase.processStubsInFile(StubProcessingHelperBase.java:62)
    at com.intellij.psi.stubs.StubProcessingHelperBase.processStubsInFile(StubProcessingHelperBase.java:40)
    at com.intellij.psi.stubs.StubIndexImpl$2.perform(StubIndexImpl.java:273)
    at com.intellij.psi.stubs.StubIndexImpl$2.perform(StubIndexImpl.java:264)
    at com.intellij.util.indexing.ValueContainer.forEach(ValueContainer.java:81)
    at com.intellij.psi.stubs.StubIndexImpl.processElements(StubIndexImpl.java:264)
    at com.intellij.psi.stubs.StubIndexImpl.processElements(StubIndexImpl.java:237)
    at com.intellij.psi.stubs.StubIndex.process(StubIndex.java:76)
    at com.intellij.psi.stubs.StubIndex.process(StubIndex.java:95)
    at com.intellij.psi.stubs.StubIndexImpl.get(StubIndexImpl.java:226)
    at com.intellij.psi.stubs.StubIndex.getElements(StubIndex.java:144)
    at com.intellij.psi.stubs.StubIndex.getElements(StubIndex.java:134)
    at com.jetbrains.php.PhpIndexImpl.getClassesByNameInScope(PhpIndexImpl.java:217)
    at com.jetbrains.php.PhpIndexImpl.getClassesByName(PhpIndexImpl.java:211)
    at com.jetbrains.php.PhpIndexImpl.getClassesByFQN(PhpIndexImpl.java:472)
    at com.jetbrains.php.lang.psi.elements.impl.PhpClassImpl.getSuperClass(PhpClassImpl.java:357)
    at com.jetbrains.php.PhpClassHierarchyUtils.getImmediateParents(PhpClassHierarchyUtils.java:286)
    at com.jetbrains.php.PhpClassHierarchyUtils.processSuperMembers(PhpClassHierarchyUtils.java:267)
    at com.jetbrains.php.lang.PhpLineMarkerProvider.findParents(PhpLineMarkerProvider.java:92)
    at com.jetbrains.php.lang.PhpLineMarkerProvider.collectSlowLineMarkers(PhpLineMarkerProvider.java:136)
    at com.intellij.codeInsight.daemon.impl.SlowLineMarkersPass.addLineMarkers(SlowLineMarkersPass.java:79)
    at com.intellij.codeInsight.daemon.impl.SlowLineMarkersPass.doCollectInformation(SlowLineMarkersPass.java:66)
    at com.intellij.codeHighlighting.TextEditorHighlightingPass.collectInformation(TextEditorHighlightingPass.java:62)
    at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass$1$1.run(PassExecutorService.java:438)
    at com.intellij.openapi.application.impl.ApplicationImpl.tryRunReadAction(ApplicationImpl.java:1143)
    at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass$1.run(PassExecutorService.java:429)
    at com.intellij.openapi.progress.impl.ProgressManagerImpl.a(ProgressManagerImpl.java:281)
    at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:233)
    at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.a(PassExecutorService.java:426)
    at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.run(PassExecutorService.java:402)
    at com.intellij.concurrency.JobLauncherImpl$VoidForkJoinTask.exec(JobLauncherImpl.java:202)
    at jsr166e.ForkJoinTask.doExec(ForkJoinTask.java:260)
    at jsr166e.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:858)
    at jsr166e.ForkJoinPool.scan(ForkJoinPool.java:1687)
    at jsr166e.ForkJoinPool.runWorker(ForkJoinPool.java:1642)
    at jsr166e.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:109)
Caused by: java.lang.ClassNotFoundException: com.intellij.ide.reporter.ConnectionException PluginClassLoader[Magicento, 2.8.6]
    at com.intellij.ide.plugins.cl.PluginClassLoader.loadClass(PluginClassLoader.java:68)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
    ... 52 more

**Comment by enriquepiatti** [comment]
Hi @yatsyukv please check this:
https://github.com/enriquepiatti/Magicento/issues/140

**Comment by yatsyukv** [comment]
Understood.
Will fallback to 8.0.1 then.

Many thanks.
